server:
  port: 8434
api_prefix: "/api/v1/"
db:
  postgres:
    url: "127.0.0.1:5432"
    user: "postgres"
    password: "postgres"
    database: "euro"
    maxPoolSize: 10
    minPoolSize: 1
    poolName: "EURO_HRM_POOL"
file_pathhrm: "/home/sysadmin/FileHRM/"
  